// English — the canonical catalog. Every other locale is typed against this,
// so missing keys are a compile error. Dyno terms/abbreviations use Bosch's own
// wording (from the \TXT\ENGL_KW table); units come from units.ts, not here.
const en = {
  // toolbar / chrome
  "app.openImg": "Open .img…",
  "app.openErg": "Open .ERG…",
  "app.tabDisk": "Disk",
  "app.tabLibrary": "Library",
  "app.printPdf": "Print / PDF…",
  "app.settings": "Settings",
  "app.shopFallback": "(no shop name)",
  // sidebar actions
  "app.importNew": "Import new ({count})",
  "app.importAll": "Import all…",
  "app.resetDisk": "Reset disk…",
  "app.runsHeader": "{count} runs",
  "app.inLibrary": "In library",
  "app.deleted": "deleted",
  "app.browseEmpty":
    "Open a Bosch FLA 203 floppy image (.img) to browse its dyno runs, or open a single .ERG file.",
  // library
  "app.searchPlaceholder": "Search description / date…",
  "app.libraryHeader": "{count} in library",
  "app.noDescription": "(no description)",
  "app.libraryEmpty": "No runs imported yet. Open a disk and “Import new”.",
  // detail / editor
  "app.description": "Description",
  "app.descPlaceholder": "Customer, vehicle, notes…",
  "app.save": "Save",
  "app.deleteFromLibrary": "Delete from library",
  "app.loading": "Loading…",
  "app.selectRun": "Select a run to view its curves.",
  // toasts
  "toast.nothingNew": "Nothing new to import — all runs are already in the library.",
  "toast.imported": "Imported {added} new run(s); skipped {skipped}.",
  "toast.importedOver": "Imported {added}, overwrote {overwritten}.",
  "toast.wiped": "Wiped {deleted} run(s). Backup saved to {path}",
  "toast.descSaved": "Description saved.",
  // dialogs
  "dialog.importAllMsg":
    "Re-import ALL {count} runs and OVERWRITE any copies already in the library?",
  "dialog.importAllTitle": "Import all / overwrite",
  "dialog.resetMsg":
    "Delete ALL dyno runs from this disk image?\n\nSettings & calibration (FLA.CFG), language tables and fonts are kept. A timestamped backup of the image is saved first.\n\n{path}",
  "dialog.resetTitle": "Reset disk",
  "dialog.deleteMsg": "Remove this run from your library? (The source disk is not touched.)",
  "dialog.deleteTitle": "Delete run",
  // settings panel
  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.units": "Units",
  "settings.unitMetric": "Metric (kW, Nm, °C)",
  "settings.unitImperial": "Imperial (bhp, lb·ft, °F)",
  "settings.revealFolder": "Open data folder",
  "settings.close": "Close",
  // dyno full terms (Bosch)
  "term.engine": "Engine power",
  "term.torque": "Torque",
  "term.wheel": "Wheel power",
  "term.loss": "Wheel power-loss",
  // dyno abbreviations (Bosch)
  "abbr.pmax": "Pmax",
  "abbr.pnim": "Prated",
  "abbr.ppyora": "Pwheel",
  "abbr.phavio": "Ploss",
  "abbr.mmax": "Tmax",
  "abbr.paine": "Press.",
  "abbr.lamp": "Temp.",
  "abbr.k": "k",
  // detail / chart
  "detail.atN": "@ n",
  "detail.noDate": "no date",
  "detail.noPower": "No power curve in this run.",
  "detail.noTorque": "No torque curve in this run.",
  "chart.sweep": "sweep →",
  "chart.versus": "versus",
  // print
  "print.reportTitle": "Dyno report",
  "print.runDate": "Run date",
  "print.generatedBy": "Generated by FLA Dynoview",
  "crop.trim": "Trim",
  "crop.reset": "Reset",
  "app.runDate": "Date",
  "app.dateNow": "Now",
  // readings override (display-only)
  "app.saveReadings": "Save readings",
  "toast.readingsSaved": "Readings saved.",
  // comparison
  "app.compare": "Compare ({count})",
  "app.comparison": "Comparison",
  "compare.selectHint": "Select 2–4 runs to overlay.",
  "compare.checkTitle": "Add to comparison",
  "compare.close": "Close comparison",
  "compare.lineNote": "Solid line = power · dashed line = torque.",
  // settings: field labels / logo / header
  "settings.fieldLabels": "Field labels",
  "settings.fieldLabelsHint": "Rename the captions shown on screen and in printouts. Leave blank for the default.",
  "settings.resetLabels": "Reset labels",
  "settings.logo": "Print logo",
  "settings.chooseLogo": "Choose image…",
  "settings.removeLogo": "Remove logo",
  "settings.headerText": "Print header text",
  "settings.headerHint": "Leave empty to use the shop name.",
} as const;

export default en;
