<script lang="ts">
  import DynoChart from "../charts/DynoChart.svelte";
  import { powerSeries, torqueSeries } from "../charts/series";
  import type { CurrentRun } from "../types";

  let { shopName = "", current }: { shopName?: string; current: CurrentRun } = $props();

  const power = $derived(powerSeries(current.channels, current.results.kDin));
  const torque = $derived(torqueSeries(current.channels, current.results.kDin));
  const r = $derived(current.results);
  const f1 = (v: number | null | undefined) => (v == null ? "—" : v.toFixed(1));
</script>

<!-- Hidden on screen; shown by the @media print rules in app.css. -->
<div id="print-report">
  <header class="pr-head">
    <div class="pr-shop">{shopName || "Dyno report"}</div>
    <div class="pr-meta">
      <span>{current.title}</span>
      <span>{current.date ?? ""}</span>
    </div>
  </header>

  {#if current.description}
    <p class="pr-desc">{current.description}</p>
  {/if}

  <table class="pr-table">
    <tbody>
      <tr><th>Pmax (engine power)</th><td>{f1(r.pmaxKw)} kW @ {r.rpmAtPmax ?? "—"} rpm</td>
          <th>Mmax (torque)</th><td>{f1(r.mmaxNm)} Nm @ {r.rpmAtMmax ?? "—"} rpm</td></tr>
      <tr><th>Pyöräteho (wheel)</th><td>{f1(r.ppyoraKw)} kW</td>
          <th>Häviöteho (loss)</th><td>{f1(r.phavioKw)} kW</td></tr>
      <tr><th>k (DIN)</th><td>{r.kDin == null ? "—" : r.kDin.toFixed(3)}</td>
          <th>Pnim (rated)</th><td>{r.pnimKw ?? "—"} kW</td></tr>
      <tr><th>Paine / Lämpötila</th><td>{r.pressureHpa ?? "—"} hPa / {r.tempC ?? "—"} °C</td>
          <th>Run date</th><td>{current.date ?? "—"}</td></tr>
    </tbody>
  </table>

  <div class="chart-block">
    <h4>Moottoriteho / Engine power [kW]</h4>
    {#if power.length}<DynoChart series={power} yLabel="kW" xLabel="sweep →" width={720} height={340} />{/if}
  </div>
  <div class="chart-block">
    <h4>Vääntömomentti / Torque [Nm]</h4>
    {#if torque.length}<DynoChart series={torque} yLabel="Nm" xLabel="sweep →" width={720} height={340} />{/if}
  </div>

  <footer class="pr-foot">Generated by FLA Dynoview</footer>
</div>

<style>
  #print-report {
    color: #000;
    background: #fff;
    font-family: system-ui, sans-serif;
  }
  .pr-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    border-bottom: 2px solid #000;
    padding-bottom: 6px;
    margin-bottom: 10px;
  }
  .pr-shop {
    font-size: 18px;
    font-weight: 700;
  }
  .pr-meta {
    display: flex;
    gap: 16px;
    font-family: ui-monospace, monospace;
    font-size: 12px;
  }
  .pr-desc {
    font-style: italic;
    margin: 0 0 10px;
  }
  .pr-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 12px;
    font-size: 12px;
  }
  .pr-table th,
  .pr-table td {
    text-align: left;
    padding: 3px 8px;
    border: 1px solid #bbb;
  }
  .pr-table th {
    background: #f0f0f0;
    font-weight: 600;
    width: 20%;
  }
  .chart-block {
    margin-bottom: 10px;
  }
  .chart-block h4 {
    margin: 0 0 4px;
    font-size: 13px;
  }
  .pr-foot {
    margin-top: 8px;
    font-size: 10px;
    color: #666;
    text-align: right;
  }
</style>
